'''
=== 3474. Lexicographically Smallest Generated String ===

You are given two strings, str1 and str2, of lengths n and m, respectively.
A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:
    - If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
    - If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".

Example 1:
    Input: str1 = "TFTF", str2 = "ab"
    Output: "ababa"
    Explanation:
    The table below represents the string "ababa"
    Index	T/F	Substring of length m
    0	'T'	"ab"
    1	'F'	"ba"
    2	'T'	"ab"
    3	'F'	"ba"
    The strings "ababa" and "ababb" can be generated by str1 and str2.
    Return "ababa" since it is the lexicographically smaller string.
Example 2:
    Input: str1 = "TFTF", str2 = "abc"
    Output: ""
    Explanation:
    No string that satisfies the conditions can be generated.
Example 3:
    Input: str1 = "F", str2 = "d"
    Output: "a"

Constraints:
    1. 1 <= n == str1.length <= 104
    2. 1 <= m == str2.length <= 500
    3. str1 consists only of 'T' or 'F'.
    4. str2 consists only of lowercase English characters.
'''
def z_algorithm(s):
    n = len(s)
    z = [0 for _ in range(n)]
    l, r = -1, -1
    for i in range(1, n):
        if i > r:
            l, r = i, i
            while r < n and s[r-l] == s[r]:
                r += 1
            z[i] = r-l
            r -= 1
        else:
            k = i - l
            if z[k] < r - i + 1:
                z[i] = z[k]
            else:
                l = i
                while r < n and s[r-l] == s[r]:
                    r += 1
                z[i] = r-l
                r -= 1
    z[0] = n
    return z
# === 2665ms && 18.4MB === #
class Solution:
    def generateString(self, str1: str, str2: str) -> str:
        n, m = len(str1), len(str2)
        z = z_algorithm(str2 + str2)[m:]
        
        ans = ["" for _ in range(n+m-1)]
        nxtT = n
        for i in range(n-1, -1, -1):
            ch = str1[i]
            if ch == "T":
                if nxtT == n or nxtT-i >= m:
                    for j in range(i, i+m):
                        ans[j] = str2[j-i]
                elif z[nxtT-i] >= m-(nxtT-i):
                    for j in range(i, nxtT):
                        ans[j] = str2[j-i]
                else:
                    return ""
                nxtT = i
                
        def is_allowed(idx, ch):
            lb = max(idx-m+1, 0)
            rb = min(n-1, idx)
            
            def is_not_same(i):
                return str2[idx-i] != ch or any(ans[i+j] != str2[j] for j in range(m) if i+j != idx)
            
            return all(is_not_same(i) for i in range(lb, rb+1))

        prefix = str2[:-1]
        for i in range(n+m-1):
            if ans[i] != "":
                if i < n and str1[i] == "F" and all(ans[i+j] == str2[j] for j in range(m)):
                    return ""
                continue
            for ch in string.ascii_lowercase:
                if is_allowed(i, ch):
                    ans[i] = ch
                    break
        return "".join(ans)