/*
=== 389. Find the Difference ===

Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:
    - Input:
    s = "abcd"
    t = "abcde"
    - Output:
    e
    - Explanation:
    'e' is the letter that was added.
*/
// === 4ms(69.92%) && 7.1MB(33.33%) === //
char findTheDifference(char * s, char * t){
    int alphabet[26] = {0};
    for(int i=0; t[i]; ++i){
        ++ alphabet[t[i] - 'a'];
    }
    for(int i=0; s[i]; ++i){
        -- alphabet[s[i] - 'a'];
    }
    for(int i=0; i<26; ++i){
        if(alphabet[i] == 1){
            return 'a' + i;
        }
    }
    return 'a';
}

